#!/bin/bash
# -*- coding: utf-8 -*-
#
# This file is part of Hubbot.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Hubbot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hubbot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Hubbot.  If not, see <http://www.gnu.org/licenses/>

HEAD="<html><body><a href=\".\">Result directory</a><pre>"
FOOT="</pre></body></html>"

function txt2html() {
    sed -u -e 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
}

function wrap() {
    cat <(echo $1) - <(echo $2)
}

function linkify() {
    sed -u -e "s,$1\(.*\),<a href=\"$2\\1\">\\0</a>,"
}

function style() {
    sed -u -e "s,$1,<span style=\"$2\">\\0</span>,g"
}

function linkimages() {
    sed -u -e "s,\\([a-zA-Z0-9-]*\\)FAIL.png,<a href=\"test/\\1FAIL.png\">\\1FAIL.png</a>,g"
}

txt2html | wrap "$HEAD" "$FOOT" | linkify "$HOME/avocado/" "$HOME/avocado/" | style PASS color:green | style FAILED color:red | linkimages
