#! /bin/bash

HEAD="<html><body><a href=\".\">Result directory</a><pre>"
FOOT="</pre></body></html>"

function txt2html() {
    sed -u -e 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
}

function wrap() {
    cat <(echo $1) - <(echo $2)
}

function linkify() {
    sed -u -e "s,$1\(.*\),<a href=\"$2\\1\">\\0</a>,"
}

function style() {
    sed -u -e "s,$1,<span style=\"$2\">\\0</span>,g"
}

function linkimages() {
    sed -u -e "s,\([a-zA-Z0-9-]*\)<span style=\"color:red\">FAIL</span>.png,<a href=\"test/\1FAIL.png\">\1FAIL.png</a>,g"
}

txt2html | wrap "$HEAD" "$FOOT" | linkify "$HOME/avocado/" "$HOME/avocado/" | style PASS color:green | style FAIL color:red | linkimages
