#! /bin/bash

SELF=vm-publish-image

targetdir=/srv/testdata/images.stage/

TEST_DATA=${TEST_DATA:-$PWD}
TEST_OS=${TEST_OS:-fedora-21}
TEST_ARCH=${TEST_ARCH:-x86_64}
TEST_RUN=./run

warning()
{
	echo >&2 "$SELF: $@"
}

silent()
{
	"$@" > /dev/null 2> /dev/null
	return $?
}

set -euf

usage()
{
	echo >&2 "usage: $SELF [-f FLAVOR]"
}

flavor=cockpit

case ${1:-} in
-f|--flavor)
	if [ $# -lt 2 ]; then
		usage
		exit 2
	fi
	flavor=$2
	shift 2
	;;
--flavor=*)
	flavor=${1#--flavor=}
	shift
	;;
--help|-h)
	usage
	exit 0
	;;
esac

TEST_IMAGE=$flavor-$TEST_OS-$TEST_ARCH

checksum_file=$TEST_IMAGE-checksum

cd "images"

if [ ! -f "$checksum_file" ]; then
    warning "$checksum_file does not exist"
    exit 1
fi

if cmp "$targetdir/$checksum_file" "$checksum_file"; then
    exit 0
fi

echo Checking sha56sums...
if ! sha256sum --quiet --check "$checksum_file"; then
    exit 1
fi

cat "$checksum_file" | while read sum file; do
  echo Publishing $file
  pv "$file" | xz -ze >"$targetdir/$file.xz"
done
cp "$checksum_file" "$targetdir/$checksum_file"
