#!/bin/bash
# -*- coding: utf-8 -*-
#
# This file is part of Hubbot.
#
# Copyright (C) 2015 Red Hat, Inc.
#
# Hubbot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Hubbot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Hubbot.  If not, see <http://www.gnu.org/licenses/>


SELF=vm-publish-images

targetdir=/srv/testdata/images

TEST_DATA=${TEST_DATA:-$PWD}

warning()
{
	echo >&2 "$SELF: $@"
}

silent()
{
	"$@" > /dev/null 2> /dev/null
	return $?
}

set -eu

publishable () {
    [ -f "$1" ] && (echo $1 | grep -q -v rhel-7)
}

maybe_publish () {
    checksum_file=$1

    if [ -f "$targetdir/$checksum_file" ]; then
      return
    fi

    cat "$checksum_file" | while read sum file; do
        echo Publishing $file
        pv "$file" | xz -ze >"$targetdir/$file.xz"
    done
    cp "$checksum_file" "$targetdir/$checksum_file"
}

maybe_unpublish () {
    checksum_file=$1

    if [ -f "$TEST_DATA/images/$checksum_file" ]; then
      return
    fi

    cat "$checksum_file" | while read sum file; do
        echo Unpublishing $file
        rm $file.xz
    done
    rm "$checksum_file"
}

cd "$TEST_DATA/images"

for f in *-checksum; do
    if publishable "$f"; then
      maybe_publish "$f"
    fi
done

cd "$targetdir"

for f in *-checksum; do
    if publishable "$f"; then
      maybe_unpublish "$f"
    fi
done
